#%RAML 1.0 DataType 
type: object
description: countrybyiso
properties:
  country:
    type: string
    example: Angola
    required: false
    description: country
  region:
    type: string
    example: Africa
    required: false
    description: region
  iso:
    type: string
    example: AO
    required: false
    description: iso
additionalProperties: false
